- name: BeegGFS Common Configuration
  hosts: client_workers, cluster_workers
  become: true
  become_user: root
  vars_files:
    - global_vars.yaml
  tasks:
  - name: Create management location
    ansible.builtin.file:
      path: /beegfs_data/mgmt
      state: directory
  - name: Configure management
    ansible.builtin.command:
      cmd: /opt/beegfs/sbin/beegfs-setup-mgmtd -p /beegfs_data/mgmt
  - name: Create metadata location
    ansible.builtin.file:
      path: /beegfs_data/md
      state: directory
  - name: Configure metadata
    ansible.builtin.command:
      cmd: "/opt/beegfs/sbin/beegfs-setup-meta -p /beegfs_data/md -m {{ DNS_name_host_node }}"
  - name: Auth file
    ansible.builtin.copy:
      src: ../gadget/connauthfile
      dest: /etc/beegfs/connauthfile
      owner: root
      group: root
      mode: 400
  - name: fix manangement conf
    ansible.builtin.replace:
      path: /etc/beegfs/beegfs-mgmtd.conf
      regexp: 'connAuthFile                           ='
      replace: 'connAuthFile=/etc/beegfs/connauthfile'
  - name: fix metadata conf
    ansible.builtin.replace:
      path: /etc/beegfs/beegfs-meta.conf
      regexp: 'connAuthFile                 ='
      replace: 'connAuthFile=/etc/beegfs/connauthfile'

- name: Start BeegGFS mgmtd and meta
  hosts: client_workers
  become: true
  become_user: root
  vars_files:
    - global_vars.yaml
  tasks:
  - name: start mgmtd
    ansible.builtin.systemd_service:
      name: beegfs-mgmtd
      state: started
      enabled: true
  - name: start medadata
    ansible.builtin.systemd_service:
      name: beegfs-meta
      state: started
      enabled: true
