- name: BeegGFS Common Configuration
  hosts: cluster_workers, client_workers
  become: true
  become_user: root
  vars_files:
    - global_vars.yaml
  tasks:
  - name: Configure client
    ansible.builtin.command:
      cmd: "/opt/beegfs/sbin/beegfs-setup-storage -p /data -m {{ DNS_name_host_node }}"
  - name: Auth file
    ansible.builtin.copy:
      src: ../gadget/connauthfile
      dest: /etc/beegfs/connauthfile
      owner: root
      group: root
      mode: 400
  - name: fix storage conf
    ansible.builtin.replace:
      path: /etc/beegfs/beegfs-storage.conf
      regexp: 'connAuthFile                 ='
      replace: 'connAuthFile=/etc/beegfs/connauthfile'
  - name: fix storage conf
    ansible.builtin.replace:
      path: /etc/beegfs/beegfs-storage.conf
      regexp: 'storeAllowFirstRunInit       = false'
      replace: 'storeAllowFirstRunInit = true'
  - name: start storage
    ansible.builtin.systemd_service:
      name: beegfs-storage
      state: started
      enabled: true
