- name: Start django
  hosts: client01
  become: true
  vars_files:
    - global_vars.yaml
  tasks:
    - name: Start django
      ansible.builtin.shell: |
        source "{{ virtualenv_path }}/bin/activate"
        cd "{{ shared_file_system }}/feedback_infer_dj"
        /beegfs_data/virtualenv/FeedBackInfer/bin/python manage.py runserver 0.0.0.0:8000
      async: 86400
      poll: 0