- name: Deploy Redis Application
  hosts: client01
  become: true
  vars_files:
    - global_vars.yaml
  tasks:
    - name: Synchronize redis.confi from host to other machine
      ansible.posix.synchronize:
        src: ../gadget/redis.conf
        dest: "{{ shared_file_system }}/redis.conf"
        recursive: true
    - name: Copy Redis Config
      ansible.builtin.copy:
        src: "{{ shared_file_system }}/redis.conf"
        dest: /etc/redis/redis.conf
        remote_src: true
        owner: 'redis'
        group: 'root'
        mode: '0644'
    - name: Restart and enable Redis service
      ansible.builtin.systemd_service:
        name: redis
        state: restarted
        enabled: true
        daemon_reload: true