- name: Configure firewalld for BeeGFS
  hosts: all
  become: true
  tasks:
  - name: install firewalld
    ansible.builtin.yum:
      name: firewalld
      state: present
  - name: Ensure firewalld is running
    ansible.builtin.service:
      name: firewalld
      state: started
      enabled: yes
  - name: open TCP port for BeeGFS services
    ansible.posix.firewalld:
      port: "{{ item }}/tcp"
      permanent: true
      state: enabled
      immediate: true
      zone: public
    loop:
      - 8003
      - 8004
      - 8005
      - 8006
      - 8008
      - 17695
      - 17183
      - 18463
  - name: Open UDP ports for BeeGFS services
    ansible.posix.firewalld:
      port: "{{ item }}/udp"
      permanent: true
      state: enabled
      immediate: true
      zone: public
    loop:
      - 8003
      - 8004
      - 8005
      - 8008

- name: Configure firewalld for flowers
  hosts: worker01
  become: true
  tasks:
  - name: open TCP port for flowers
    ansible.posix.firewalld:
      port: "4000/tcp"
      zone: public
      permanent: true
      state: enabled
      immediate: true
  - name: Set up port forwarding from 80 to 4000
    ansible.posix.firewalld:
      rich_rule: rule family=ipv4 forward-port port=80 protocol=tcp to-port=4000
      zone: public
      permanent: true
      immediate: true
      state: enabled

- name: Configure django and redis
  hosts: client01
  become: true
  tasks:
  - name: open TCP port for redis
    ansible.posix.firewalld:
      port: "6379/tcp"
      zone: internal
      permanent: true
      state: enabled
      immediate: true
  - name: Set up port forwarding from 80 to 8000
    ansible.posix.firewalld:
      rich_rule: rule family=ipv4 forward-port port=80 protocol=tcp to-port=8000
      zone: public
      permanent: true
      immediate: true
      state: enabled
