- name: Download kaggle dataset on client node
  hosts: client01
  vars_files:
    - global_vars.yaml
  tasks:
    - name: install unzip
      ansible.builtin.dnf:
        name: unzip
        state: latest
      become: true

    - name: Ensure input directory exists
      ansible.builtin.file:
        path: /beegfs-FeedBackInfer/input/feedback-prize-effectiveness
        state: directory

    - name: download the competition dataset
      ansible.builtin.shell: |
        source "{{ virtualenv_path }}/bin/activate"
        kaggle competitions download -c feedback-prize-effectiveness -p /beegfs-FeedBackInfer/
    - name: Ensure feedback-prize-effectiveness directory exists
      ansible.builtin.file:
        path: /beegfs-FeedBackInfer/input/feedback-prize-effectiveness
        state: directory
    - name: Unzip competition dataset
      ansible.builtin.unarchive:
        src: /beegfs-FeedBackInfer/feedback-prize-effectiveness.zip
        dest: /beegfs-FeedBackInfer/input/feedback-prize-effectiveness
        remote_src: yes

    - name: Download debertav3base dataset
      ansible.builtin.shell: |
        source "{{ virtualenv_path }}/bin/activate"
        kaggle datasets download debarshichanda/debertav3base -p /beegfs-FeedBackInfer/
    - name: Ensure debertav3base directory exists
      ansible.builtin.file:
        path: /beegfs-FeedBackInfer/input/debertav3base
        state: directory
    - name: Unzip debertav3base dataset
      ansible.builtin.unarchive:
        src: /beegfs-FeedBackInfer/debertav3base.zip
        dest: /beegfs-FeedBackInfer/input/debertav3base
        remote_src: yes

    - name: Ensure pytorch-feedback-deberta-v3-baseline directory exists
      ansible.builtin.file:
        path: /beegfs-FeedBackInfer/input/pytorch-feedback-deberta-v3-baseline
        state: directory
    - name: Download and unzip kernel output
      ansible.builtin.shell: |
        source "{{ virtualenv_path }}/bin/activate"
        kaggle kernels output debarshichanda/pytorch-feedback-deberta-v3-baseline -p /beegfs-FeedBackInfer/input/pytorch-feedback-deberta-v3-baseline
