- name: Install basic packages
  hosts: client01
  become: true
  vars_files:
    - global_vars.yaml
  tasks:
  - name: Install firewalld
    ansible.builtin.dnf:
      name: firewalld
      state: latest
  - name: start firewalld
    ansible.builtin.systemd_service:
      name: firewalld
      state: started
      enabled: true
  - name: Open port 6379 for Redis
    firewalld:
      port: "6379/tcp"
      permanent: true
      state: enabled

  - name: Install redis
    ansible.builtin.dnf:
      name: redis
      state: latest
