- name: Install basic packages
  hosts: client01
  become: true
  vars_files:
    - global_vars.yaml
  tasks:
  - name: Install firewalld
    ansible.builtin.dnf:
      name: firewalld
      state: latest
  - name: Install redis
    ansible.builtin.dnf:
      name: redis
      state: latest
  - name: Install redis-server
    ansible.builtin.dnf:
      name: redis-server
      state: latest
