- name: Install basic packages
  hosts: client01
  become: true
  vars_files:
    - global_vars.yaml
  tasks:
  - name: Install dependencies
    ansible.builtin.package:
      name: python3-apt
      state: present

  - name: Install firewalld
    ansible.builtin.dnf:
      name: firewalld
      state: latest
  - name: start firewalld
    ansible.builtin.systemd_service:
      name: firewalld
      state: started
      enabled: true

  - name: Install redis
    ansible.builtin.dnf:
      name: redis
      state: latest
  - name: Install redis-server
    ansible.builtin.apt:
      name: redis-server
      state: latest
