- name: Mount filesystem
  hosts: all
  become: true
  tasks:
    - name: create a mount point for the data volume
      ansible.builtin.file:
        path: /data
        state: directory
        mode: '0755'
    - name: format the volumen as ext4
      community.general.filesystem:
        dev: /dev/nvme1n1
        fstype: ext4
      become: true
    - name: mount the filesystem
      ansible.posix.mount:
        name: /data
        src: /dev/nvme1n1
        fstype: ext4
        state: mounted
      become: true