- name: Setup keys
  hosts: all
  tasks:
    - name: Set host keys
      ansible.posix.authorized_key:
        user: ec2-user
        state: present
        key: "{{ lookup('file', '/home/ec2-user/.ssh/host_key.pub') }}"
