- name: Folder creation
  hosts: client01
  become: true
  vars_files:
    - global_vars.yaml
  tasks:
    - name: Ensure celery_code directory exists
      ansible.builtin.file:
        path: "{{ shared_file_system }}/celery_code"
        state: directory
    - name: Ensure log_output directory exists
      ansible.builtin.file:
        path: "{{ shared_file_system }}/celery_code/log"
        state: directory
    - name: Ensure output directory exists
      ansible.builtin.file:
        path: "{{ shared_file_system }}/output"
        state: directory
    - name: Synchronize celery_code from host to other machine
      ansible.posix.synchronize:
        src: ../celery_code
        dest: "{{ shared_file_system }}"
        recursive: true

- name: Start celery workers
  hosts: client01, worker01
  become: true
  vars_files:
    - global_vars.yaml
  tasks:
    - name: Start Celery workers
      ansible.builtin.shell: |
        source "{{ virtualenv_path }}/bin/activate"
        cd "{{ shared_file_system }}"
        celery -A celery_code.src.celery_app worker --loglevel=INFO --logfile="{{ shared_file_system }}/celery_code/log/{{ inventory_hostname }}.log"