- name: Remove all files in /data directory
  hosts: all
  become: true
  tasks:
    - name: Find all files and directories in /data
      ansible.builtin.find:
        paths: "/data"
        recurse: yes
      register: files_and_dirs

    - name: Remove all files found in /data directory
      ansible.builtin.file:
        path: "{{ item.path }}"
        state: absent
      loop: "{{ files.files }}"
      when: files_and_dirs.matched > 0
