- name: Shutdown Celery Workers
  hosts: all
  become: true
  vars_files:
    - ../global_vars.yaml
  tasks:
    - name: Gracefully shutdown Celery workers
      ansible.builtin.shell: |
        source "{{ virtualenv_path }}/bin/activate"
        cd "{{ shared_file_system }}/feedback_infer_dj"
        celery -A feedback_infer_dj control shutdown

