- name: Stop and Clean BeeGFS
  hosts: all
  become: true
  tasks:
    - name: Stop BeeGFS services
      ansible.builtin.systemd:
        name: "{{ item }}"
        state: stopped
      loop:
        - beegfs-helperd
        - beegfs-client
        - beegfs-mgmtd
        - beegfs-meta
        - beegfs-storage
