- name: Unmount and Remove /beegfs directory
  hosts: all
  become: true
  tasks:
    - name: Unmount /beegfs
      ansible.posix.mount:
        path: /beegfs-FeedBackInfer
        state: unmounted
    - name: Remove /beegfs directory
      ansible.builtin.file:
        path: /beegfs-FeedBackInfer
        state: absent
    - name: unmount the filesystem
      ansible.posix.mount:
        name: /beegfs_data
        src: /dev/nvme1n1
        fstype: ext4
        state: unmounted
      become: true
    - name: Clean BeeGFS storage directory
      ansible.builtin.file:
        path: /beegfs_data
        state: absent
    - name: Stop BeeGFS services
      ansible.builtin.systemd:
        name: "{{ item }}"
        state: stopped
      loop:
        - beegfs-helperd
        - beegfs-client
        - beegfs-mgmtd
        - beegfs-meta
        - beegfs-storage 
