- name: Unmount and Remove /beegfs directory
  hosts: all
  become: true
  tasks:
    - name: Unmount /beegfs
      ansible.posix.mount:
        path: /beegfs
        state: unmounted

    - name: Remove /beegfs directory
      ansible.builtin.file:
        path: /beegfs
        state: absent
