- name: Unmount and Remove /beegfs directory
  hosts: localhost, all
  become: true
  tasks:
    - name: Unmount /beegfs
      ansible.posix.mount:
        path: /beegfs-FeedBackInfer
        state: unmounted

    - name: Remove /beegfs directory
      ansible.builtin.file:
        path: /beegfs-FeedBackInfer
        state: absent

    - name: Find all .conf files in /etc/beegfs
      ansible.builtin.find:
        paths: /etc/beegfs
        patterns: '*.conf'
      register: found_conf_files

    - name: Remove found .conf files
      ansible.builtin.file:
        path: "{{ item.path }}"
        state: absent
      loop: "{{ found_conf_files.files }}"

- name: Stop and Clean BeeGFS
  hosts: localhost, all
  become: true
  tasks:
    - name: Stop BeeGFS services
      ansible.builtin.systemd:
        name: "{{ item }}"
        state: stopped
      loop:
        - beegfs-helperd
        - beegfs-client
        - beegfs-meta
        - beegfs-storage
        - beegfs-mgmtd

    - name: Clean BeeGFS storage directory
      ansible.builtin.file:
        path: "/beegfs_data/target"
        state: absent

    - name: Clean BeeGFS meta directory
      ansible.builtin.file:
        path: "/beegfs_data/md"
        state: absent

    - name: Clean BeeGFS mgmtd directory
      ansible.builtin.file:
        path: "/beegfs_data/mgmt"
        state: absent
