- name: Unmount filesystem
  hosts: all
  become: true
  tasks:
    - name: unmount the filesystem
      ansible.posix.mount:
        name: /beegfs-data
        src: /dev/nvme1n1
        fstype: ext4
        state: unmounted
      become: true
    - name: remove the mount point
      ansible.builtin.file:
        path: /beegfs-data
        state: absent
      become: true
